In [3]:
import numpy as np
arr = np.arange(1,13)
print("Original:")
print(arr)

print("Original Shape")
print(arr.shape)

arr2 =  arr.reshape(3,4)

print("Reshaped:")
print(arr2)

print("New Shape:")
print(arr2.shape)

arr3 = arr.reshape(4,3)

print(arr3)

arr4 = arr.reshape(2,6)

print(arr4)

Original:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape
(12,)
Reshaped:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New Shape:
(3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [5]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print("Original:")
print(arr)

print("Original Shape:")
print(arr.shape)
flat = arr.flatten()

print("Flattened:")
print(flat)

print("Flattened Shape:")
print(flat.shape)

arr2 = np.array([
    [1,2],
    [3,4],
    [5,6]
])

print(arr2.flatten())

Original:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Original Shape:
(3, 3)
Flattened:
[10 20 30 40 50 60 70 80 90]
Flattened Shape:
(9,)
[1 2 3 4 5 6]


In [6]:
import numpy as np

arr = np.array([
    [10,20],
    [30,40]
])

flat = arr.flatten()

flat[0] = 999

print("Original array:")
print(arr)

print("Flattened array:")
print(flat)

arr2 = np.array([
    [10,20],
    [30,40]
])

r = arr2.ravel()

r[0] = 999

print("Original array:")
print(arr2)

print("Ravel array:")
print(r)

Original array:
[[10 20]
 [30 40]]
Flattened array:
[999  20  30  40]
Original array:
[[999  20]
 [ 30  40]]
Ravel array:
[999  20  30  40]


In [7]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])

print("Original:")
print(arr)

print("Original Shape:")
print(arr.shape)

transposed = arr.T

print("Transposed:")
print(transposed)

print("Transposed Shape:")
print(transposed.shape)

print(arr.transpose())

Original:
[[10 20 30]
 [40 50 60]]
Original Shape:
(2, 3)
Transposed:
[[10 40]
 [20 50]
 [30 60]]
Transposed Shape:
(3, 2)
[[10 40]
 [20 50]
 [30 60]]


In [8]:
import numpy as np
data = np.arange(1,13)
print("Original:")
print(data)
matrix = data.reshape(3,4)
print("\nReshaped:")
print(matrix)
print("\nTranspose:")
print(matrix.T)
print("\nFlatten:")
print(matrix.flatten())
print("\nRavel:")
print(matrix.ravel())

Original:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Ravel:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
