In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
import numpy as np
arr1 = np.array([5, 10, 15, 20, 25])
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

(5,)
1
5
int64


In [7]:
import numpy as np
arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[10 20 30]
 [40 50 60]]
(2, 3)
2
6
int64


In [8]:
import numpy as np
arr = np.array([
    [100,200,300],
    [400,500,600]
])
print(arr[0,0])
print(arr[0,2])
print(arr[1,1])
print(arr[1,2])

100
300
500
600


In [9]:
import numpy as np
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,:])
print(arr[:,2])
print(arr[1:3,:])
print(arr[:,0:2])

[10 20 30]
[30 60 90]
[[40 50 60]
 [70 80 90]]
[[10 20]
 [40 50]
 [70 80]]


In [1]:
import numpy as np
arr = np.array([2,4,6,8])
print(arr + 10)
print(arr - 1)
print(arr * 5)
print(arr / 2)

[12 14 16 18]
[1 3 5 7]
[10 20 30 40]
[1. 2. 3. 4.]


In [2]:
import numpy as np

list1 = [10,20,30]

arr1 = np.array([10,20,30])

print(list1 * 3)

print(arr1 * 3)

[10, 20, 30, 10, 20, 30, 10, 20, 30]
[30 60 90]
