In [1]:
import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

print("Array 1:", arr1)
print("Array 2:", arr2)

result = np.concatenate((arr1, arr2))

print("Combined:", result)
print("Shape:", result.shape)

a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

result = np.concatenate((a,b,c))

print(result)

Array 1: [10 20 30]
Array 2: [40 50 60]
Combined: [10 20 30 40 50 60]
Shape: (6,)
[1 2 3 4 5 6]


In [1]:
import numpy as np

a = np.array([10,20,30])
b = np.array([40,50,60])

vertical = np.vstack((a,b))

print("Vertical:")
print(vertical)

print("Shape:")
print(vertical.shape)

horizontal = np.hstack((a,b))

print("Horizontal:")
print(horizontal)

print("Shape:")
print(horizontal.shape)

Vertical:
[[10 20 30]
 [40 50 60]]
Shape:
(2, 3)
Horizontal:
[10 20 30 40 50 60]
Shape:
(6,)


In [4]:
import numpy as np

arr = np.array([10,20,30,40,50])

print("Original:")
print(arr)

print("\nUsing array_split:")

parts = np.array_split(arr, 2)

print(parts)

print("\nPart 1:")
print(parts[0])

print("\nPart 2:")
print(parts[1])

arr2 = np.array([1,2,3,4,5,6,7])

parts2 = np.array_split(arr2, 3)

print(parts2)

Original:
[10 20 30 40 50]

Using array_split:
[array([10, 20, 30]), array([40, 50])]

Part 1:
[10 20 30]

Part 2:
[40 50]
[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [5]:
import numpy as np

sales_jan = np.array([
    [101,500],
    [102,700],
    [103,300]
])

sales_feb = np.array([
    [104,800],
    [105,600]
])

all_sales = np.vstack((sales_jan, sales_feb))

print("All Sales:")
print(all_sales)

print("Shape:")
print(all_sales.shape)

batches = np.array_split(all_sales, 2)

print("\nBatches:")
print(batches)

All Sales:
[[101 500]
 [102 700]
 [103 300]
 [104 800]
 [105 600]]
Shape:
(5, 2)

Batches:
[array([[101, 500],
       [102, 700],
       [103, 300]]), array([[104, 800],
       [105, 600]])]
