In [1]:
import numpy as np
arr1 = np.random.rand(5)
arr2 = np.random.rand(2,4)
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[0.93290833 0.45080116 0.0568481  0.89952855 0.68837001]
[[0.09116486 0.8542751  0.02307151 0.19201556]
 [0.97675315 0.95983131 0.67983888 0.04298871]]
(5,)
(2, 4)


In [2]:
import numpy as np
arr1 = np.random.randint(1,50,6)
arr2 = np.random.randint(100,200,(3,2))
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[48 38 18  8 36 49]
[[121 149]
 [126 119]
 [100 170]]
(6,)
(3, 2)


In [3]:
import numpy as np

subjects = ["Python","SQL","Spark","AWS","Airflow"]
sample = np.random.choice(subjects,4)
print(sample)
print(sample.shape)

['Python' 'Airflow' 'Spark' 'Python']
(4,)


In [4]:
import numpy as np
np.random.seed(50)
arr1 = np.random.randint(1,20,5)
np.random.seed(50)
arr2 = np.random.randint(1,20,5)
print(arr1)
print(arr2)
print(arr1 == arr2)

[17  1 12 14  2]
[17  1 12 14  2]
[ True  True  True  True  True]
