In [1]:
import numpy as np

employees = np.array([
    [101, 50000, 2, 78],
    [102, 75000, 4, 91],
    [103, 45000, 1, 65],
    [104, 90000, 6, 95],
    [105, 60000, 3, 82],
    [106, 40000, 1, 58],
    [107, 85000, 5, 88],
    [108, 55000, 2, 72],
    [109, 95000, 7, 97],
    [110, 70000, 4, 85]
])

In [13]:
print(employees)

total_employee = np.size(employees[:,0])
print(total_employee)
total_column = np.size(employees[0,:])
print(total_column)
total = np.shape(employees)
print(total)
print(employees[:,0])
print(employees[:,1])
print(employees[:,3])
salary = employees[:,1]
print(np.mean(salary))
print(np.max(salary))
print(np.min(salary))
performance = employees[:,3]
print(np.mean(performance))

[[  101 50000     2    78]
 [  102 75000     4    91]
 [  103 45000     1    65]
 [  104 90000     6    95]
 [  105 60000     3    82]
 [  106 40000     1    58]
 [  107 85000     5    88]
 [  108 55000     2    72]
 [  109 95000     7    97]
 [  110 70000     4    85]]
10
4
(10, 4)
[101 102 103 104 105 106 107 108 109 110]
[50000 75000 45000 90000 60000 40000 85000 55000 95000 70000]
[78 91 65 95 82 58 88 72 97 85]
66500.0
95000
40000
81.1


In [15]:
high_sal = employees[employees[:,1] > 70000]
print(high_sal)

[[  102 75000     4    91]
 [  104 90000     6    95]
 [  107 85000     5    88]
 [  109 95000     7    97]]


In [16]:
Performance_score = employees[employees[:,3] >= 85]
print(Performance_score)

[[  102 75000     4    91]
 [  104 90000     6    95]
 [  107 85000     5    88]
 [  109 95000     7    97]
 [  110 70000     4    85]]


In [18]:
experience = employees[employees[:,2] >= 5]
print(experience)

[[  104 90000     6    95]
 [  107 85000     5    88]
 [  109 95000     7    97]]


In [23]:
high_sal_perf = employees[(employees[:,1] > 70000) & (employees[:,3] >= 85)]
print(high_sal_perf)

[[  102 75000     4    91]
 [  104 90000     6    95]
 [  107 85000     5    88]
 [  109 95000     7    97]]


In [27]:
salary_status = np.where(salary >= 70000,"High","Low")
print(salary_status)

['Low' 'High' 'Low' 'High' 'Low' 'Low' 'High' 'Low' 'High' 'High']


In [30]:
print(np.sum(salary > 70000))
print(np.sum(employees[:,3] >= 85 ))
high_performers = employees[employees[:,3] >= 85]
high_performer_salaries = high_performers[:,1]
np.mean(high_performer_salaries)

4
5


np.float64(83000.0)

In [36]:
salary_status = np.where(
    salary >= 70000,
    "High",
    "Normal"
)
print(salary_status)
Performance_status = np.where(employees[:,3] >= 85, "Excellent", "Average")
print(Performance_status)
print(np.sum(Performance_status == "Excellent"))
maxi = np.max(employees[:,3])
print(maxi)
Best_Emp = np.where(employees[:,3] == maxi)
print(employees[Best_Emp])


['Normal' 'High' 'Normal' 'High' 'Normal' 'Normal' 'High' 'Normal' 'High'
 'High']
['Average' 'Excellent' 'Average' 'Excellent' 'Average' 'Average'
 'Excellent' 'Average' 'Excellent' 'Excellent']
5
97
[[  109 95000     7    97]]


In [38]:
batches = np.array_split(employees, 3)
print(batches)
print("Number of batches:", len(batches))

[array([[  101, 50000,     2,    78],
       [  102, 75000,     4,    91],
       [  103, 45000,     1,    65],
       [  104, 90000,     6,    95]]), array([[  105, 60000,     3,    82],
       [  106, 40000,     1,    58],
       [  107, 85000,     5,    88]]), array([[  108, 55000,     2,    72],
       [  109, 95000,     7,    97],
       [  110, 70000,     4,    85]])]
Number of batches: 3


In [45]:
batch_report = []
for i, batch in enumerate(batches):
    employee_count = batch.shape[0]
    avg_salary = np.mean(batch[:,1])
    avg_performance = np.mean(batch[:,3])
    highest_performance = np.max(batch[:,3])

    print(f"\nBatch {i + 1}")
    print(f"Employees: {employee_count}")
    print(f"Average salary {avg_salary}")
    print(f"Average Performance: {avg_performance}")
    print(f"Highest Performance: {highest_performance}")

    row = [
        i+1,
        employee_count,
        avg_salary,
        avg_performance,
        highest_performance
    ]

    batch_report.append(row)
batch_report = np.array(batch_report)

print(batch_report)
print(batch_report.shape)


Batch 1
Employees: 4
Average salary 65000.0
Average Performance: 82.25
Highest Performance: 95

Batch 2
Employees: 3
Average salary 61666.666666666664
Average Performance: 76.0
Highest Performance: 88

Batch 3
Employees: 3
Average salary 73333.33333333333
Average Performance: 84.66666666666667
Highest Performance: 97
[[1.00000000e+00 4.00000000e+00 6.50000000e+04 8.22500000e+01
  9.50000000e+01]
 [2.00000000e+00 3.00000000e+00 6.16666667e+04 7.60000000e+01
  8.80000000e+01]
 [3.00000000e+00 3.00000000e+00 7.33333333e+04 8.46666667e+01
  9.70000000e+01]]
(3, 5)


In [48]:
max_avg_salary = np.max(batch_report[:,2])
print(max_avg_salary)

best_salary_batch = np.where(
    batch_report[:,2] == max_avg_salary
)

print(best_salary_batch)

highest_avg_perf = np.max(batch_report[:,3])
print(highest_avg_perf)

high_avg_batch = np.where(
    batch_report[:,3] == highest_avg_perf
)
print(high_avg_batch)

max_performance = np.max(employees[:,3])

best_employee_index = np.where(
    employees[:,3] == max_performance
)[0]

best_employee = employees[best_employee_index]

print(best_employee)

excellent_count = np.sum(employees[:,3] >= 85)

percentage = (
    excellent_count / employees.shape[0]
) * 100

print("Excellent employees:", excellent_count)
print("Percentage:", percentage)

overall_avg_salary = np.mean(employees[:,1])

overall_avg_performance = np.mean(employees[:,3])

print("===== FINAL EMPLOYEE ANALYTICS =====")

print("Overall Average Salary:", overall_avg_salary)
print("Overall Average Performance:", overall_avg_performance)
print("Excellent Employees:", excellent_count)
print("Excellent Employee Percentage:", percentage)
print("Best Employee:", best_employee)

73333.33333333333
(array([2]),)
84.66666666666667
(array([2]),)
[[  109 95000     7    97]]
Excellent employees: 5
Percentage: 50.0
===== FINAL EMPLOYEE ANALYTICS =====
Overall Average Salary: 66500.0
Overall Average Performance: 81.1
Excellent Employees: 5
Excellent Employee Percentage: 50.0
Best Employee: [[  109 95000     7    97]]


In [49]:
highest_avg_perf = np.max(batch_report[:,3])

high_avg_batch = np.where(
    batch_report[:,3] == highest_avg_perf
)[0]

print("Highest Average Performance:", highest_avg_perf)
print("Best Performance Batch:", high_avg_batch + 1)

Highest Average Performance: 84.66666666666667
Best Performance Batch: [3]
