In [1]:
import numpy as np

arr = np.array([10,20,30,40])

print("Original:", arr)

print("Add 5:", arr + 5)

print("Subtract 2:", arr - 2)

print("Multiply by 3:", arr * 3)

print("Divide by 2:", arr / 2)

Original: [10 20 30 40]
Add 5: [15 25 35 45]
Subtract 2: [ 8 18 28 38]
Multiply by 3: [ 30  60  90 120]
Divide by 2: [ 5. 10. 15. 20.]


In [2]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])

print("Original:")
print(arr)

print("Add 5:")
print(arr + 5)

print("Multiply by 2:")
print(arr * 2)

print("Subtract 10:")
print(arr - 10)

Original:
[[10 20 30]
 [40 50 60]]
Add 5:
[[15 25 35]
 [45 55 65]]
Multiply by 2:
[[ 20  40  60]
 [ 80 100 120]]
Subtract 10:
[[ 0 10 20]
 [30 40 50]]


In [6]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])

values = np.array([1,2,3])

print("Array shape:", arr.shape)
print("Values shape:", values.shape)

print(arr + values)

values2 = np.array([1,2])

#print(arr + values2) gives broadcasting error

Array shape: (2, 3)
Values shape: (3,)
[[11 22 33]
 [41 52 63]]


In [7]:
import numpy as np

prices = np.array([
    [100],
    [200],
    [300]
])

tax = np.array([10,20])

print("Prices shape:", prices.shape)
print("Tax shape:", tax.shape)

print(prices + tax)

Prices shape: (3, 1)
Tax shape: (2,)
[[110 120]
 [210 220]
 [310 320]]
