In [2]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print("Original:")
print(arr)

print("Indexes 0, 2, 5:")
print(arr[[0,2,5]])

print("Indexes 1, 3, 4:")
print(arr[[1,3,4]])

indexes = np.array([0,3,5])

print(arr[indexes])

Original:
[10 20 30 40 50 60]
Indexes 0, 2, 5:
[10 30 60]
Indexes 1, 3, 4:
[20 40 50]
[10 40 60]


In [3]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print("Original:")
print(arr)

print("\nRows 0 and 2:")
print(arr[[0,2]])

print("\nRows 1 and 2:")
print(arr[[1,2]])

Original:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Rows 0 and 2:
[[10 20 30]
 [70 80 90]]

Rows 1 and 2:
[[40 50 60]
 [70 80 90]]


In [4]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

rows = np.array([0,1,2])
cols = np.array([2,1,0])

print("Selected values:")
print(arr[rows, cols])

Selected values:
[30 50 70]


In [5]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

indexes = np.where(arr > 30)

print("Indexes:")
print(indexes)

print("Values:")
print(arr[indexes])

Indexes:
(array([3, 4, 5]),)
Values:
[40 50 60]


In [7]:
import numpy as np

salaries = np.array([30000,45000,60000,75000,90000])

result = np.where(
    salaries >= 60000,
    "High",
    "Low"
)

print("Salaries:")
print(salaries)

print("Classification:")
print(result)

scores = np.array([45,67,82,91,38,76])

result = np.where(scores >= 50, "Pass", "Fail")

print(result)

Salaries:
[30000 45000 60000 75000 90000]
Classification:
['Low' 'Low' 'High' 'High' 'High']
['Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass']
