In [1]:
import numpy as np
arr1 = np.zeros(5)
arr2 = np.zeros((2,4))
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(5,)
(2, 4)


In [2]:
import numpy as np
arr1 = np.ones(6)
arr2 = np.ones((3,4))
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(6,)
(3, 4)


In [3]:
import numpy as np
arr1 = np.full(6,100)
arr2 = np.full((3,4), -5)
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[100 100 100 100 100 100]
[[-5 -5 -5 -5]
 [-5 -5 -5 -5]
 [-5 -5 -5 -5]]
(6,)
(3, 4)


In [5]:
import numpy as np
arr1 = np.arange(10)
arr2 = np.arange(5,15)
arr3 = np.arange(2,20,3)
print(arr1)
print(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[ 2  5  8 11 14 17]


In [7]:
import numpy as np
arr1 = np.linspace(0,20,5)
arr2 = np.linspace(10,100,10)
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[ 0.  5. 10. 15. 20.]
[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
(5,)
(10,)


In [8]:
import numpy as np
arr = np.arange(12)
print(arr)
arr2 = arr.reshape(4,3)
print(arr2)
print(arr2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [9]:
import numpy as np
arr1 = np.eye(3)
arr2 = np.eye(5)
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(3, 3)
(5, 5)
