In [2]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(arr)
print(arr.sum())

[ 2  4  6  8 10]
30


In [3]:
import numpy as np

arr = np.array([15,25,35,45,55])
print(arr)
print("Sum:", arr.sum())
print("Mean:", arr.mean())

[15 25 35 45 55]
Sum: 175
Mean: 35.0


In [4]:
import numpy as np
arr = np.array([65, 42, 89, 15, 73])
print(arr)
print("Minimum:", arr.min())

print("Maximum:", arr.max())

print("Sum:", arr.sum())

print("Mean:", arr.mean())

[65 42 89 15 73]
Minimum: 15
Maximum: 89
Sum: 284
Mean: 56.8


In [5]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

print("Sum:", arr.sum())

print("Mean:", arr.mean())

print("Minimum:", arr.min())

print("Maximum:", arr.max())

print("Standard Deviation:", arr.std())

print("Variance:", arr.var())

[10 20 30 40 50]
Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Standard Deviation: 14.142135623730951
Variance: 200.0


In [6]:
import numpy as np
arr =  np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
print(arr)

print("Sum Axis 0:", arr.sum(axis=0))

print("Sum Axis 1:", arr.sum(axis=1))

print("Mean Axis 0:", arr.mean(axis=0))

print("Mean Axis 1:", arr.mean(axis=1))

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Sum Axis 0: [60 75 90]
Sum Axis 1: [ 30  75 120]
Mean Axis 0: [20. 25. 30.]
Mean Axis 1: [10. 25. 40.]
